# Generated by Django 6.0.4 on 2026-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('products_list', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-transaction_time']},
        ),
    ]
